### ISSUE TITLE
这个和marker平移，旋转有什么区别吗？

### ISSUE THREAD

**Issue by liupeng826** [amap-demo/android-smooth-move#1]
高德地图Android SDK(3D地图) V4.0.02016-09-23
功能
Marker类新增平移、旋转、缩放等动画效果；

4.0更新了这些功能，和你这个demo有区别吗？

**Comment by qiyy** [comment]
不是一回事，4.0更新功能是Marker的一些动画效果，这个平滑移动是marker的实际位置和角度的变化；使用场景也不太一样，动画效果是为了一些场景的过渡效果或者展示效果更炫，平滑移动是为了解决如果点要沿着线移动（类似导航、轨迹回放等）时，整个移动效果平滑，不会有跳、偏离线、以及角度显示不合适的问题

**Comment by liupeng826** [comment]
能不能做一个swift版本的?一直没有一个完整的swift 3D地图轨迹平滑移动的实例

**Comment by qiyy** [comment]
好 我们这边可以排下这个需求

**Comment by xesam** [comment]
1. Marker不在视界内，并且没有设置 showInfoWindow() 的时候（此时 Marker 已经被移除了），Animation 就不会执行，这个问题最严重。。
3. 无法停止 Marker 的 Animation，现在我只能再发起一个非常短的平移动画来干掉正在执行的动画，万不得已。。
